### PR TITLE
NN-4481: alerts add visor

### PR DESCRIPTION
**Pull request by jamesgrant-moj**
**Add VISOR alert to the list of DPS alerts**

Acceptance Criteria
• Unsaved changes

The alert should be visible in the 

Global Prisoner Search – for example [HMPPS Digital Services - Sign in](https://digital-dev.prison.service.justice.gov.uk/prisoner-search?keywords=&location=MDI)

Prisoner Profile –  for example [HMPPS Digital Services - Sign in](https://digital-dev.prison.service.justice.gov.uk/prisoner/G6123VU) 

ViSOR Nominal (PVN) is an existing alert that can be added to a prisoner profile. The type of alert is ‘MAPPP Case' and the alert is called 'ViSOR nominal’.

The alert label will appear with the other labels at the top of the Prisoner profile, when the alert has been added to a prisoner’s record.

The label should read ViSOR in capital letters (lower case i) and be #003078 coloured text with the same colour border.

The label should appear in alphabetical order like the existing labels.

### CODE REVIEW

**Review by HamHazJustice — COMMENTED** [review]
Not so familiar with this area but wondering do we need a specific presence test for VISOR / PVR ?

**Review by natclamp-moj — APPROVED** [review]
Looks good to me! Well done for navigating this giant repository 😅

**Comment by jamesgrant-moj** [comment]
> Not so familiar with this area but wondering do we need a specific presence test for VISOR / PVR ?

Thanks for taking a look.

The presence of ViSOR & PVN is covered in test prisonerSearch.test.ts - line 573

**Comment by jamesgrant-moj** [comment]
> Looks good to me! Well done for navigating this giant repository 😅

Thanks for taking a look. I'll merge it in.

Giant is an understatement 😅

**Pull request merged**
